title: Reynaldo's learning site
author: Reynaldo
email: reyabreu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is an incredible sandbox website for learning more about static pages hosting 
  and creation. I might eventually add soemthing useful, but as for the time being this 
  is just a playground.

# social links
twitter_username: rey_abreu # DO NOT include the @ character, or else the build will fail!
github_username: reyabreu # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
